$axure.loadCurrentPage({
  "url":"page14.html",
  "generationDate":new Date(1477474338299.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69973a5630a1433fb424e6f2ce43d60b",
    "type":"Axure:Page",
    "name":"page14",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"61ef93f1055c41c2adeef4269580280c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":10},
            "size":{
              "width":480,
              "height":210},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c76392385f34aa7a05c0aa9010cf018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":10},
                "size":{
                  "width":480,
                  "height":210},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page14/u0.png"}},
{
          "id":"57397a32a41446bc9d31f4c92959b394",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":87,
              "y":38},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af10071fc4004abbbcbd8bd8f40cb14e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":87,
                  "y":38},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4488e1aa82c7494a81e5340cdcbc6d95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":87,
              "y":105},
            "size":{
              "width":359,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8b9561480ee49c1966fd690717e81b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":87,
                  "y":105},
                "size":{
                  "width":359,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a33a99e83924b3fbe99c220670ee186",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":166},
            "size":{
              "width":110,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"new"},
{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"883348a2f3494a90886dc05bf14ac0da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":87},
            "size":{
              "width":336,
              "height":6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260f402670d341e68aba1c6be6afc33a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":87},
                "size":{
                  "width":336,
                  "height":6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"312d026b2dad43ff808b8aabcc55fbbe",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":166},
            "size":{
              "width":110,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "61ef93f1055c41c2adeef4269580280c":{
      "scriptId":"u0"},
    "6c76392385f34aa7a05c0aa9010cf018":{
      "scriptId":"u1"},
    "57397a32a41446bc9d31f4c92959b394":{
      "scriptId":"u2"},
    "af10071fc4004abbbcbd8bd8f40cb14e":{
      "scriptId":"u3"},
    "4488e1aa82c7494a81e5340cdcbc6d95":{
      "scriptId":"u4"},
    "c8b9561480ee49c1966fd690717e81b3":{
      "scriptId":"u5"},
    "6a33a99e83924b3fbe99c220670ee186":{
      "scriptId":"u6"},
    "883348a2f3494a90886dc05bf14ac0da":{
      "scriptId":"u7"},
    "260f402670d341e68aba1c6be6afc33a":{
      "scriptId":"u8"},
    "312d026b2dad43ff808b8aabcc55fbbe":{
      "scriptId":"u9"}}});