$axure.loadCurrentPage({
  "url":"常见问题解答.html",
  "generationDate":new Date(1477474344595.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dd06435ae8d54d40bbec117a02e32420",
    "type":"Axure:Page",
    "name":"常见问题解答",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d57674a8e29244d3ab7d37914e6686a8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":30,
              "y":125},
            "size":{
              "width":1176,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a54373481850463aa5999d262e3a5a0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":30,
                  "y":125},
                "size":{
                  "width":1176,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息提示/u0.png"}},
{
          "id":"d03d7db015f041f9a169073995700ce0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":151,
              "y":136},
            "size":{
              "width":100,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fcb52ebea344a61b93ac98b9cb3c4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":151,
                  "y":136},
                "size":{
                  "width":100,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 page4",
                      "target":{
                        "targetType":"page",
                        "url":"page4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息提示/u2.png"}},
{
          "id":"ed4f088e14c74a7faa3e4bb6a21f5a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":166,
              "y":144},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8011f1296bc94f5693ec0b4755299103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":144},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 page4",
                      "target":{
                        "targetType":"page",
                        "url":"page4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70df30b78ec64b3cb8762daf4dbd8cf5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF009DD9},
{
                  "color":0xFF009DD9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":262,
              "y":135},
            "size":{
              "width":125,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094b666c49774cafb540053296ca1dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF009DD9},
{
                      "color":0xFF009DD9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":262,
                  "y":135},
                "size":{
                  "width":125,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/常见问题解答/u6.png"}},
{
          "id":"86937d3460114ac3a7a2fa008a702c4f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":41,
              "y":136},
            "size":{
              "width":100,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f3a5d712b70461caecd23cf19daf3de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":41,
                  "y":136},
                "size":{
                  "width":100,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息提示/u2.png"}},
{
          "id":"8e5d2ab94b1a4b198945027806068f02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":56,
              "y":144},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c096678737b84ba096f9884a4deaf5a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":144},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0a9c078d5af4bd5aaaa9f3f6d07c0dd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1470,
              "height":116},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7186018d9940cfbf26a906f2a56317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1470,
                  "height":116},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u0.png"}},
{
          "id":"39efef3942454d56bd75077ddb3652af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'汉真广标 regular', '汉真广标'",
            "location":{
              "x":133,
              "y":42},
            "size":{
              "width":199,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27b54eaee3fb4e74add3b2ad13afbe99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'汉真广标 regular', '汉真广标'",
                "location":{
                  "x":133,
                  "y":42},
                "size":{
                  "width":199,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7943908d61141f0a3ae56b93a11b496",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":136},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9cb009428e7466c8ed2afce338bab3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":136},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b0e24ccc0904fa5b8354960296c7840",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":30,
              "y":175},
            "size":{
              "width":1176,
              "height":595},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab14f47a396b48bb85794a9ca48da55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":30,
                  "y":175},
                "size":{
                  "width":1176,
                  "height":595},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page5/u16.png"}},
{
          "id":"f053d265bf74485b9dc48976aa26e7ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":191},
            "size":{
              "width":1165,
              "height":559},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e3e5fc3cb234e68b10afa378a39cc78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":191},
                "size":{
                  "width":1165,
                  "height":559},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评审流程/u20.png"}},
{
          "id":"42d6ceca461c471bbee63a8959bb8953",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":277,
              "y":143},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ee7269d904849cf8bcb9972fd82edc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":143},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e7d6137c5e643fa97bbd0230e2addb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1206,
              "y":126},
            "size":{
              "width":294,
              "height":644},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2c14473ee92469a861d60bc697d35d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1206,
                  "y":126},
                "size":{
                  "width":294,
                  "height":644},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page5/u395.png"}},
{
          "id":"f5dbe6f57fb049f28c0ffe33f460ff87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1043,
              "y":51},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d6c2d19b4b842018fdbd9d190656bc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":51},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be23026451a34fc3aec9ff7235fc2820",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1388,
              "y":45},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238b4fe07817430585881feef68aca47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1388,
                  "y":45},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1de8ecc815348e288d9785c467e11da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1402,
              "y":51},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1251171076724b6984111df12e590d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1402,
                  "y":51},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79456140d66940c4a19ccbd6720296d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11aa5c48222942ffb25d5a77a753ce78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96da73612f7b4ec3ae2da2c8f8be5ca4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1348,
              "y":45},
            "size":{
              "width":32,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6428de088a0b41e39eed2e161ff0942f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1348,
                  "y":45},
                "size":{
                  "width":32,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"f750c551736f4891af0d32891cb3d58f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1184,
              "y":51},
            "size":{
              "width":146,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b984d3248ae49d88c7325321e004206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1184,
                  "y":51},
                "size":{
                  "width":146,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0bc140d5f844e68b59864b1c51e6f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1334,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dd49c61075e4e5296000635fe3e297b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1334,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10caa2e91148459a8524da2d09ef47c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1060,
              "y":83},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc08a7d3588043cc920dc8c91fd97a5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":83},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e510e823acc749f49437515596ca0de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":78},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9aafb47398d4cb7b301c3514c5cc32c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":78},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50bc33894abb4fbf98ea71ebbf9fe207",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1185,
              "y":83},
            "size":{
              "width":175,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff48cd5f2a904d559af11f6dd666efd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1185,
                  "y":83},
                "size":{
                  "width":175,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf334e629ca2452d97d1c7799309604a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":220},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef65526b04843e08a33e6a672b91bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":220},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u46.png"}},
{
          "id":"193c2a68fdb345c3a4dbd668b7097437",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":230},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8642b4e610e496989c04c4c565b0d62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":230},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeddbc18474c47e899bc2531e5487a06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":166},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b3cc81bee54cc79847cca681d58127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":166},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u50.png"}},
{
          "id":"218c5f68e91546bf8b8cb61a1062880e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":176},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f3c714a0f7447e9797bfdc96216ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":176},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"767ab4a396264b25811bf42dcb9d1281",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":275},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7302e297a4e94e4cb691c09a5e36ae48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":275},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u54.png"}},
{
          "id":"2de8c53a036a462c87cab71840aacb2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":285},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1bfd1e5cace468184730c2bd08198a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":285},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e44132303824d0681dd7794b073b44d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":220},
            "size":{
              "width":1099,
              "height":500},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82aa992a18ea48bfaa2849a2dbb1603f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":220},
                "size":{
                  "width":1099,
                  "height":500},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dotted"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/常见问题解答/u58.png"}},
{
          "id":"cff27f67f0a74d178ab04e292e1db9be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":243},
            "size":{
              "width":1050,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7983a1e45cf4bf5918715ac11dff02b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":243},
                "size":{
                  "width":1050,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d57674a8e29244d3ab7d37914e6686a8":{
      "scriptId":"u0"},
    "a54373481850463aa5999d262e3a5a0b":{
      "scriptId":"u1"},
    "d03d7db015f041f9a169073995700ce0":{
      "scriptId":"u2"},
    "7fcb52ebea344a61b93ac98b9cb3c4bb":{
      "scriptId":"u3"},
    "ed4f088e14c74a7faa3e4bb6a21f5a4e":{
      "scriptId":"u4"},
    "8011f1296bc94f5693ec0b4755299103":{
      "scriptId":"u5"},
    "70df30b78ec64b3cb8762daf4dbd8cf5":{
      "scriptId":"u6"},
    "094b666c49774cafb540053296ca1dd5":{
      "scriptId":"u7"},
    "86937d3460114ac3a7a2fa008a702c4f":{
      "scriptId":"u8"},
    "9f3a5d712b70461caecd23cf19daf3de":{
      "scriptId":"u9"},
    "8e5d2ab94b1a4b198945027806068f02":{
      "scriptId":"u10"},
    "c096678737b84ba096f9884a4deaf5a2":{
      "scriptId":"u11"},
    "b0a9c078d5af4bd5aaaa9f3f6d07c0dd":{
      "scriptId":"u12"},
    "4f7186018d9940cfbf26a906f2a56317":{
      "scriptId":"u13"},
    "39efef3942454d56bd75077ddb3652af":{
      "scriptId":"u14"},
    "27b54eaee3fb4e74add3b2ad13afbe99":{
      "scriptId":"u15"},
    "f7943908d61141f0a3ae56b93a11b496":{
      "scriptId":"u16"},
    "f9cb009428e7466c8ed2afce338bab3c":{
      "scriptId":"u17"},
    "1b0e24ccc0904fa5b8354960296c7840":{
      "scriptId":"u18"},
    "ab14f47a396b48bb85794a9ca48da55d":{
      "scriptId":"u19"},
    "f053d265bf74485b9dc48976aa26e7ec":{
      "scriptId":"u20"},
    "9e3e5fc3cb234e68b10afa378a39cc78":{
      "scriptId":"u21"},
    "42d6ceca461c471bbee63a8959bb8953":{
      "scriptId":"u22"},
    "3ee7269d904849cf8bcb9972fd82edc3":{
      "scriptId":"u23"},
    "4e7d6137c5e643fa97bbd0230e2addb4":{
      "scriptId":"u24"},
    "f2c14473ee92469a861d60bc697d35d8":{
      "scriptId":"u25"},
    "f5dbe6f57fb049f28c0ffe33f460ff87":{
      "scriptId":"u26"},
    "3d6c2d19b4b842018fdbd9d190656bc8":{
      "scriptId":"u27"},
    "be23026451a34fc3aec9ff7235fc2820":{
      "scriptId":"u28"},
    "238b4fe07817430585881feef68aca47":{
      "scriptId":"u29"},
    "b1de8ecc815348e288d9785c467e11da":{
      "scriptId":"u30"},
    "1251171076724b6984111df12e590d98":{
      "scriptId":"u31"},
    "79456140d66940c4a19ccbd6720296d5":{
      "scriptId":"u32"},
    "11aa5c48222942ffb25d5a77a753ce78":{
      "scriptId":"u33"},
    "96da73612f7b4ec3ae2da2c8f8be5ca4":{
      "scriptId":"u34"},
    "6428de088a0b41e39eed2e161ff0942f":{
      "scriptId":"u35"},
    "f750c551736f4891af0d32891cb3d58f":{
      "scriptId":"u36"},
    "6b984d3248ae49d88c7325321e004206":{
      "scriptId":"u37"},
    "e0bc140d5f844e68b59864b1c51e6f44":{
      "scriptId":"u38"},
    "3dd49c61075e4e5296000635fe3e297b":{
      "scriptId":"u39"},
    "10caa2e91148459a8524da2d09ef47c3":{
      "scriptId":"u40"},
    "cc08a7d3588043cc920dc8c91fd97a5e":{
      "scriptId":"u41"},
    "e510e823acc749f49437515596ca0de0":{
      "scriptId":"u42"},
    "d9aafb47398d4cb7b301c3514c5cc32c":{
      "scriptId":"u43"},
    "50bc33894abb4fbf98ea71ebbf9fe207":{
      "scriptId":"u44"},
    "ff48cd5f2a904d559af11f6dd666efd6":{
      "scriptId":"u45"},
    "bf334e629ca2452d97d1c7799309604a":{
      "scriptId":"u46"},
    "aef65526b04843e08a33e6a672b91bcb":{
      "scriptId":"u47"},
    "193c2a68fdb345c3a4dbd668b7097437":{
      "scriptId":"u48"},
    "b8642b4e610e496989c04c4c565b0d62":{
      "scriptId":"u49"},
    "eeddbc18474c47e899bc2531e5487a06":{
      "scriptId":"u50"},
    "44b3cc81bee54cc79847cca681d58127":{
      "scriptId":"u51"},
    "218c5f68e91546bf8b8cb61a1062880e":{
      "scriptId":"u52"},
    "c9f3c714a0f7447e9797bfdc96216ed3":{
      "scriptId":"u53"},
    "767ab4a396264b25811bf42dcb9d1281":{
      "scriptId":"u54"},
    "7302e297a4e94e4cb691c09a5e36ae48":{
      "scriptId":"u55"},
    "2de8c53a036a462c87cab71840aacb2b":{
      "scriptId":"u56"},
    "e1bfd1e5cace468184730c2bd08198a0":{
      "scriptId":"u57"},
    "1e44132303824d0681dd7794b073b44d":{
      "scriptId":"u58"},
    "82aa992a18ea48bfaa2849a2dbb1603f":{
      "scriptId":"u59"},
    "cff27f67f0a74d178ab04e292e1db9be":{
      "scriptId":"u60"},
    "f7983a1e45cf4bf5918715ac11dff02b":{
      "scriptId":"u61"}}});