$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1477474336399.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd3cabd446754dda870b3d9b3b35dba7",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b816b1d1b7a64f028edc2fc14623c19f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1470,
              "height":116},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e157b677494f109e2cab1e130e692f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1470,
                  "height":116},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u0.png"}},
{
          "id":"fa511a77a149434a97b491a754b33d8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'汉真广标 regular', '汉真广标'",
            "fontSize":"36px",
            "location":{
              "x":133,
              "y":42},
            "size":{
              "width":223,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acdda14aeb3945d5beeee642934b0d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'汉真广标 regular', '汉真广标'",
                "fontSize":"36px",
                "location":{
                  "x":133,
                  "y":42},
                "size":{
                  "width":223,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f443d9c1fc504e4e8cbdc363e6f9d764",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1043,
              "y":51},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3298770aff124cd5a4d655790367101c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":51},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da1c610f60ec4ea585fbe6d805c136b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1388,
              "y":45},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de3242df46174f41ad4150c91a095b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1388,
                  "y":45},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56203f153b8e4bb68db5728db54e5461",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1402,
              "y":51},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2c67bb2ecd4ad1acbaabaaaa0a13e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1402,
                  "y":51},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3822525b94f34c748a18919cfd9e8bae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":136},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21370e896e294a73b62abb52c6f91a37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":136},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"becc7b2a5cfe4a4995da09d2b5130e88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1206,
              "y":126},
            "size":{
              "width":294,
              "height":594},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f92fe08ae32446f3b53788fa373ba6f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1206,
                  "y":126},
                "size":{
                  "width":294,
                  "height":594},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u12.png"}},
{
          "id":"b3c37f276ca44377befa00b76ef03135",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":126},
            "size":{
              "width":1176,
              "height":594},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10164e465bba4b0fa8c98932f6295848",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":126},
                "size":{
                  "width":1176,
                  "height":594},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u14.png"}},
{
          "id":"9c7f9d88c28946b1863a1daec9a8ac0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":140},
            "size":{
              "width":1117,
              "height":580},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41cefe25616b43e1ac2284e690340ffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":140},
                "size":{
                  "width":1117,
                  "height":580},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u16.png"}},
{
          "id":"4bb27dbb30e64c9c9e7897b1b3a88b38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b07461bcb82749d284b87a5c00a7c7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5d64ec5f72b432c93b1e913b5fbc869",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1348,
              "y":45},
            "size":{
              "width":32,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9268ac29b64dc4bbc658ff6e2f3449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1348,
                  "y":45},
                "size":{
                  "width":32,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"483ff4c854d84bf4b16836d78ad163ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1184,
              "y":51},
            "size":{
              "width":146,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"708c5fae0eff47e19ac72edbca973e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1184,
                  "y":51},
                "size":{
                  "width":146,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5daa64f1f5940a7bfffa54d906149e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1334,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b5c252580e410facbb62b7711536c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1334,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b335bfa480c849a8b63f7ca0732431c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1060,
              "y":83},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd3575674734a8fb3ff5d155b2d2d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":83},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6473307c9c0425a9508fa5fc0cdcf97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":78},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82635799aec4c9099468e2bac358211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":78},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbae4fa246d34999af1dcf5fc4313b07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1185,
              "y":83},
            "size":{
              "width":175,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510df718834649e19a5b844087544c73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1185,
                  "y":83},
                "size":{
                  "width":175,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b31dcb8d6a3a45da9a695c432d55132f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":460,
              "y":320.5},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51882904968649c5aadff4db0e69383a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":460,
                  "y":320.5},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cbc56d5103d4f3caae949b5f38614b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":460,
              "y":380},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d80e2a173a7425486ef4167ca60777c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":460,
                  "y":380},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b1678a0204447e182f4d845aaaf8bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":643,
              "y":380},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c340d579bac246478502b4b7e3e0cfe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":643,
                  "y":380},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4d2452e87ca4e13a6c6afede279b8bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":460,
              "y":418},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e603672c65854af3b2996a03f5ba6033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":460,
                  "y":418},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f565ac9dd12c4a1d9545b436d5b17feb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":646,
              "y":418},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b5296adc4342d8b97d05844d336521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":646,
                  "y":418},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74f1f487e8b14ae1bc6ee8f340a1891e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":460,
              "y":460},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49d8a43b34e14a388ab927294f9111a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":460,
                  "y":460},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b6ce4c8a945466b948569ee624126c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":500.5},
            "size":{
              "width":144,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 2",
                      "target":{
                        "targetType":"page",
                        "url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"97128f25cc42415c8ebbf8e53ac86dca",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":500.5},
            "size":{
              "width":144,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8d1d3fcb11864afcbd6d62cb4d0d2731",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":220},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a4b13e2d92b46d6b06f5cb8cb793c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":220},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u46.png"}},
{
          "id":"1be2e83e267c4ed68ea458a1cfb03c74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":230},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"920b38743fdd4a20aa8c63fc4f2b7c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":230},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0010c65c1244465f9e98a41174057ba2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":166},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93207536af82489c88127c0c1cd1c0b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":166},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u50.png"}},
{
          "id":"c8ddb33b386745d096fc1dd1fff033d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":176},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf0b414aace497f873eb7e53faa9ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":176},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ec7ac26b2314f3a81f1ab073d992b17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":275},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f00bdcc1e8a74cc5942d12cac433e4c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":275},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u54.png"}},
{
          "id":"77ea83b6f46c4d8dae38ede7afff49ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":285},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf011e4abf1425eaa317009dc15bcf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":285},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b816b1d1b7a64f028edc2fc14623c19f":{
      "scriptId":"u0"},
    "83e157b677494f109e2cab1e130e692f":{
      "scriptId":"u1"},
    "fa511a77a149434a97b491a754b33d8c":{
      "scriptId":"u2"},
    "acdda14aeb3945d5beeee642934b0d75":{
      "scriptId":"u3"},
    "f443d9c1fc504e4e8cbdc363e6f9d764":{
      "scriptId":"u4"},
    "3298770aff124cd5a4d655790367101c":{
      "scriptId":"u5"},
    "da1c610f60ec4ea585fbe6d805c136b0":{
      "scriptId":"u6"},
    "de3242df46174f41ad4150c91a095b82":{
      "scriptId":"u7"},
    "56203f153b8e4bb68db5728db54e5461":{
      "scriptId":"u8"},
    "3b2c67bb2ecd4ad1acbaabaaaa0a13e9":{
      "scriptId":"u9"},
    "3822525b94f34c748a18919cfd9e8bae":{
      "scriptId":"u10"},
    "21370e896e294a73b62abb52c6f91a37":{
      "scriptId":"u11"},
    "becc7b2a5cfe4a4995da09d2b5130e88":{
      "scriptId":"u12"},
    "f92fe08ae32446f3b53788fa373ba6f0":{
      "scriptId":"u13"},
    "b3c37f276ca44377befa00b76ef03135":{
      "scriptId":"u14"},
    "10164e465bba4b0fa8c98932f6295848":{
      "scriptId":"u15"},
    "9c7f9d88c28946b1863a1daec9a8ac0e":{
      "scriptId":"u16"},
    "41cefe25616b43e1ac2284e690340ffc":{
      "scriptId":"u17"},
    "4bb27dbb30e64c9c9e7897b1b3a88b38":{
      "scriptId":"u18"},
    "b07461bcb82749d284b87a5c00a7c7d5":{
      "scriptId":"u19"},
    "b5d64ec5f72b432c93b1e913b5fbc869":{
      "scriptId":"u20"},
    "be9268ac29b64dc4bbc658ff6e2f3449":{
      "scriptId":"u21"},
    "483ff4c854d84bf4b16836d78ad163ab":{
      "scriptId":"u22"},
    "708c5fae0eff47e19ac72edbca973e28":{
      "scriptId":"u23"},
    "c5daa64f1f5940a7bfffa54d906149e1":{
      "scriptId":"u24"},
    "a6b5c252580e410facbb62b7711536c9":{
      "scriptId":"u25"},
    "b335bfa480c849a8b63f7ca0732431c3":{
      "scriptId":"u26"},
    "ccd3575674734a8fb3ff5d155b2d2d10":{
      "scriptId":"u27"},
    "d6473307c9c0425a9508fa5fc0cdcf97":{
      "scriptId":"u28"},
    "b82635799aec4c9099468e2bac358211":{
      "scriptId":"u29"},
    "cbae4fa246d34999af1dcf5fc4313b07":{
      "scriptId":"u30"},
    "510df718834649e19a5b844087544c73":{
      "scriptId":"u31"},
    "b31dcb8d6a3a45da9a695c432d55132f":{
      "scriptId":"u32"},
    "51882904968649c5aadff4db0e69383a":{
      "scriptId":"u33"},
    "2cbc56d5103d4f3caae949b5f38614b3":{
      "scriptId":"u34"},
    "6d80e2a173a7425486ef4167ca60777c":{
      "scriptId":"u35"},
    "2b1678a0204447e182f4d845aaaf8bf6":{
      "scriptId":"u36"},
    "c340d579bac246478502b4b7e3e0cfe7":{
      "scriptId":"u37"},
    "d4d2452e87ca4e13a6c6afede279b8bf":{
      "scriptId":"u38"},
    "e603672c65854af3b2996a03f5ba6033":{
      "scriptId":"u39"},
    "f565ac9dd12c4a1d9545b436d5b17feb":{
      "scriptId":"u40"},
    "d1b5296adc4342d8b97d05844d336521":{
      "scriptId":"u41"},
    "74f1f487e8b14ae1bc6ee8f340a1891e":{
      "scriptId":"u42"},
    "49d8a43b34e14a388ab927294f9111a7":{
      "scriptId":"u43"},
    "9b6ce4c8a945466b948569ee624126c2":{
      "scriptId":"u44"},
    "97128f25cc42415c8ebbf8e53ac86dca":{
      "scriptId":"u45"},
    "8d1d3fcb11864afcbd6d62cb4d0d2731":{
      "scriptId":"u46"},
    "9a4b13e2d92b46d6b06f5cb8cb793c49":{
      "scriptId":"u47"},
    "1be2e83e267c4ed68ea458a1cfb03c74":{
      "scriptId":"u48"},
    "920b38743fdd4a20aa8c63fc4f2b7c09":{
      "scriptId":"u49"},
    "0010c65c1244465f9e98a41174057ba2":{
      "scriptId":"u50"},
    "93207536af82489c88127c0c1cd1c0b6":{
      "scriptId":"u51"},
    "c8ddb33b386745d096fc1dd1fff033d1":{
      "scriptId":"u52"},
    "baf0b414aace497f873eb7e53faa9ffd":{
      "scriptId":"u53"},
    "6ec7ac26b2314f3a81f1ab073d992b17":{
      "scriptId":"u54"},
    "f00bdcc1e8a74cc5942d12cac433e4c6":{
      "scriptId":"u55"},
    "77ea83b6f46c4d8dae38ede7afff49ca":{
      "scriptId":"u56"},
    "7bf011e4abf1425eaa317009dc15bcf4":{
      "scriptId":"u57"}}});