$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1477474336832.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78a444d0a729435ba3f5a0e2871b15e9",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"81a6104ba9c84c399395475c610c5850",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1470,
              "height":116},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4988cf59528d45cd87cb26554c7f250b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1470,
                  "height":116},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u0.png"}},
{
          "id":"3b1071a32b074acc8e8fe8a42a45077b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'汉真广标 regular', '汉真广标'",
            "fontSize":"36px",
            "location":{
              "x":133,
              "y":42},
            "size":{
              "width":223,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177341cc9eec4c29ad22ed8aabc05dca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'汉真广标 regular', '汉真广标'",
                "fontSize":"36px",
                "location":{
                  "x":133,
                  "y":42},
                "size":{
                  "width":223,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3289ba902ca4051ba284e16a7b3df1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1043,
              "y":51},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7866a2e7abb467e8a9c8ff53d4aef4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":51},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0158999c629c4bc48b4a505f617bdcd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1388,
              "y":45},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd5ad9883a1b48febc77fc6f9e4c8c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1388,
                  "y":45},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d62ade35d74a4dbc93f2679fd8ce41c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1402,
              "y":51},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"179e22efb7554586aa91951ac99b0c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1402,
                  "y":51},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57cd66a203184baf933186dd0797c52c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":136},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e572d5a14fcd4530a8e33de34889dcfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":136},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8cd4492843b40c8854ed4a108140019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1206,
              "y":126},
            "size":{
              "width":294,
              "height":594},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ab3f3c12c248e3ad3033a90e2fe97f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1206,
                  "y":126},
                "size":{
                  "width":294,
                  "height":594},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u12.png"}},
{
          "id":"eaaabb543561468fae091204a242dc96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":126},
            "size":{
              "width":1176,
              "height":594},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afd07e3e37054d9187f705f19eccb25c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":126},
                "size":{
                  "width":1176,
                  "height":594},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u14.png"}},
{
          "id":"e17c64dddc6b44edbdfbcc6b867c060a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":140},
            "size":{
              "width":1117,
              "height":580},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aa4a1cafd444d85a1c5d408fbc665e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":140},
                "size":{
                  "width":1117,
                  "height":580},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u16.png"}},
{
          "id":"6525a1a4f8954082a949586c03d6a117",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7fbf151a7aa4fc49fe87cdfcf5008f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3494c2d4659a4691b84fb1f4a9978033",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1348,
              "y":45},
            "size":{
              "width":32,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"541edeba944a44ffa67e7cc6764c4637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1348,
                  "y":45},
                "size":{
                  "width":32,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"b04e930a7abc43e6a3c2c74e20325a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1184,
              "y":51},
            "size":{
              "width":146,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b28cbae7234ec6958fca24d6b328d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1184,
                  "y":51},
                "size":{
                  "width":146,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"799ee971dabf47fb9aa13291eb25cfde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1334,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bb2cb473f674cb19176b468c87b96c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1334,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7252a69b46e4b298a1c2f32ba3e22e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1060,
              "y":83},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732549bcda804cbda92f43c662b95649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":83},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c54f1c861c9a4d93ace18e507d7f6774",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":78},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b0555581a44659835c076288819e7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":78},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e27694283d348e59db64203b34822f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1185,
              "y":83},
            "size":{
              "width":175,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ecf63afcc6041958d3d8d492dc7d24b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1185,
                  "y":83},
                "size":{
                  "width":175,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a5d3f91656d40c9819a4621ce106f22",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":384,
              "y":240},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c42e6ceedf46d4b078c044fe0f1a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":384,
                  "y":240},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7ef1162e3da4c2690a7f37f3163967b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":384,
              "y":300},
            "size":{
              "width":446,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aedd9e661fa4d669bda2b19b83c1e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":384,
                  "y":300},
                "size":{
                  "width":446,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd1f1393520f4d73805835321e929aad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":585},
            "size":{
              "width":144,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信息提示",
                      "target":{
                        "targetType":"page",
                        "url":"信息提示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b61b88974da840b7989a3e8e3878d445",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":646,
              "y":585},
            "size":{
              "width":144,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b188cbce2ce940559241df7845248592",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":220},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2378e62c7f74b7a80a3c0e4bcf2f9cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":220},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u46.png"}},
{
          "id":"8f8fba0eae5f47769ffb956de9ebb11c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":230},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adcac00a59c24bf0bc88ebe3334b8900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":230},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b6e300d8e1945b2a6f41b5152845f2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":166},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eda009c040949cb81a7ff5400080f49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":166},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u50.png"}},
{
          "id":"ce68ba178a9c4d80a934238e3be449cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":176},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c57b66df75604b62913c0e67b944c94b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":176},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c792a460f254164a0c4c5c466826971",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":275},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647cca0c296a4f48872f6f110d708c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":275},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u54.png"}},
{
          "id":"239d89e419dd496995c23f68bb2146d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":285},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13dcc051a16b4b74b431c531d3ba5ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":285},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "81a6104ba9c84c399395475c610c5850":{
      "scriptId":"u0"},
    "4988cf59528d45cd87cb26554c7f250b":{
      "scriptId":"u1"},
    "3b1071a32b074acc8e8fe8a42a45077b":{
      "scriptId":"u2"},
    "177341cc9eec4c29ad22ed8aabc05dca":{
      "scriptId":"u3"},
    "c3289ba902ca4051ba284e16a7b3df1c":{
      "scriptId":"u4"},
    "c7866a2e7abb467e8a9c8ff53d4aef4a":{
      "scriptId":"u5"},
    "0158999c629c4bc48b4a505f617bdcd3":{
      "scriptId":"u6"},
    "fd5ad9883a1b48febc77fc6f9e4c8c8b":{
      "scriptId":"u7"},
    "d62ade35d74a4dbc93f2679fd8ce41c3":{
      "scriptId":"u8"},
    "179e22efb7554586aa91951ac99b0c9e":{
      "scriptId":"u9"},
    "57cd66a203184baf933186dd0797c52c":{
      "scriptId":"u10"},
    "e572d5a14fcd4530a8e33de34889dcfb":{
      "scriptId":"u11"},
    "f8cd4492843b40c8854ed4a108140019":{
      "scriptId":"u12"},
    "11ab3f3c12c248e3ad3033a90e2fe97f":{
      "scriptId":"u13"},
    "eaaabb543561468fae091204a242dc96":{
      "scriptId":"u14"},
    "afd07e3e37054d9187f705f19eccb25c":{
      "scriptId":"u15"},
    "e17c64dddc6b44edbdfbcc6b867c060a":{
      "scriptId":"u16"},
    "8aa4a1cafd444d85a1c5d408fbc665e0":{
      "scriptId":"u17"},
    "6525a1a4f8954082a949586c03d6a117":{
      "scriptId":"u18"},
    "a7fbf151a7aa4fc49fe87cdfcf5008f1":{
      "scriptId":"u19"},
    "3494c2d4659a4691b84fb1f4a9978033":{
      "scriptId":"u20"},
    "541edeba944a44ffa67e7cc6764c4637":{
      "scriptId":"u21"},
    "b04e930a7abc43e6a3c2c74e20325a8b":{
      "scriptId":"u22"},
    "d4b28cbae7234ec6958fca24d6b328d9":{
      "scriptId":"u23"},
    "799ee971dabf47fb9aa13291eb25cfde":{
      "scriptId":"u24"},
    "6bb2cb473f674cb19176b468c87b96c5":{
      "scriptId":"u25"},
    "d7252a69b46e4b298a1c2f32ba3e22e6":{
      "scriptId":"u26"},
    "732549bcda804cbda92f43c662b95649":{
      "scriptId":"u27"},
    "c54f1c861c9a4d93ace18e507d7f6774":{
      "scriptId":"u28"},
    "71b0555581a44659835c076288819e7e":{
      "scriptId":"u29"},
    "6e27694283d348e59db64203b34822f9":{
      "scriptId":"u30"},
    "0ecf63afcc6041958d3d8d492dc7d24b":{
      "scriptId":"u31"},
    "3a5d3f91656d40c9819a4621ce106f22":{
      "scriptId":"u32"},
    "27c42e6ceedf46d4b078c044fe0f1a78":{
      "scriptId":"u33"},
    "d7ef1162e3da4c2690a7f37f3163967b":{
      "scriptId":"u34"},
    "4aedd9e661fa4d669bda2b19b83c1e9f":{
      "scriptId":"u35"},
    "dd1f1393520f4d73805835321e929aad":{
      "scriptId":"u36"},
    "b61b88974da840b7989a3e8e3878d445":{
      "scriptId":"u37"},
    "b188cbce2ce940559241df7845248592":{
      "scriptId":"u38"},
    "c2378e62c7f74b7a80a3c0e4bcf2f9cc":{
      "scriptId":"u39"},
    "8f8fba0eae5f47769ffb956de9ebb11c":{
      "scriptId":"u40"},
    "adcac00a59c24bf0bc88ebe3334b8900":{
      "scriptId":"u41"},
    "2b6e300d8e1945b2a6f41b5152845f2b":{
      "scriptId":"u42"},
    "8eda009c040949cb81a7ff5400080f49":{
      "scriptId":"u43"},
    "ce68ba178a9c4d80a934238e3be449cd":{
      "scriptId":"u44"},
    "c57b66df75604b62913c0e67b944c94b":{
      "scriptId":"u45"},
    "0c792a460f254164a0c4c5c466826971":{
      "scriptId":"u46"},
    "647cca0c296a4f48872f6f110d708c04":{
      "scriptId":"u47"},
    "239d89e419dd496995c23f68bb2146d2":{
      "scriptId":"u48"},
    "13dcc051a16b4b74b431c531d3ba5ea4":{
      "scriptId":"u49"}}});