$axure.loadCurrentPage({
  "url":"评审流程.html",
  "generationDate":new Date(1477474344451.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"76229655830f4769b1df2bcf8147d42b",
    "type":"Axure:Page",
    "name":"评审流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"35fb7b0bad424874a48fa12b7a0a3811",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":30,
              "y":125},
            "size":{
              "width":1176,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b2e69149476478a895046ad4779ced9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":30,
                  "y":125},
                "size":{
                  "width":1176,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息提示/u0.png"}},
{
          "id":"f2e765746ba04275b44f50aeea1286c6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":151,
              "y":136},
            "size":{
              "width":100,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6e064aa87f4556a4d36ead92e90c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":151,
                  "y":136},
                "size":{
                  "width":100,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 page4",
                      "target":{
                        "targetType":"page",
                        "url":"page4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息提示/u2.png"}},
{
          "id":"5fc64044291f48a0a6fc27456f0ef42a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":166,
              "y":144},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d64aec64a49a4a378aa527af5820d7fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":144},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 page4",
                      "target":{
                        "targetType":"page",
                        "url":"page4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34f712fbef9d4433b051675901c11ee6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF009DD9},
{
                  "color":0xFF009DD9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":266,
              "y":135},
            "size":{
              "width":100,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e7fcc90b1c54554b4813bc07bb1ddbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF009DD9},
{
                      "color":0xFF009DD9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":266,
                  "y":135},
                "size":{
                  "width":100,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page4/u4.png"}},
{
          "id":"72fb0da261a549f1b06e11f08449a18c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":41,
              "y":136},
            "size":{
              "width":100,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b03b580487ab42abb23aeae1fd78cfe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":41,
                  "y":136},
                "size":{
                  "width":100,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息提示/u2.png"}},
{
          "id":"551f4d9b679e4f8ba0c052769c290213",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":56,
              "y":144},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9af48934a846a780aa888789861152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":144},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fcfaa273d184ee08bf6a78ff937a610",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1470,
              "height":116},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6de8cc9d10204c789ff3a22daae6189b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1470,
                  "height":116},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u0.png"}},
{
          "id":"d2a413c9ac804dc7a116cd17724e03d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'汉真广标 regular', '汉真广标'",
            "location":{
              "x":133,
              "y":42},
            "size":{
              "width":199,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1861558fc9bf416ca26389d317415a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'汉真广标 regular', '汉真广标'",
                "location":{
                  "x":133,
                  "y":42},
                "size":{
                  "width":199,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e2985c17d324f96bf7b36db1aeb1816",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":136},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f3e08ca4484239b18f1764c4ce581d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":136},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7224456d222491a935f72f7d8f12ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":30,
              "y":175},
            "size":{
              "width":1176,
              "height":595},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9334a59f5e4429a61817b9fbb99c86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":30,
                  "y":175},
                "size":{
                  "width":1176,
                  "height":595},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page5/u16.png"}},
{
          "id":"83dcada727b0418bbc8110f281107452",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":191},
            "size":{
              "width":1165,
              "height":559},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc7dece7c6b8451c80dd885e53266ee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":191},
                "size":{
                  "width":1165,
                  "height":559},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评审流程/u20.png"}},
{
          "id":"be2f0919ba02447a87441f6e5745e9a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":281,
              "y":143},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa277e2f473446d809e73c0f5571a11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":281,
                  "y":143},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b67cf3005b6e486b9b57b58e19507da5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1206,
              "y":126},
            "size":{
              "width":294,
              "height":644},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9da2e4730c54cb6bda71fa8d189a55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1206,
                  "y":126},
                "size":{
                  "width":294,
                  "height":644},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page5/u395.png"}},
{
          "id":"6d3e60a1a2dc4edabf26676139ba9fc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1043,
              "y":51},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b8ba60956d45c6af42657cb46bc7cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":51},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47c889ecc5104da788a1940e8c3bed58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1388,
              "y":45},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b006e01e422742d5acfa8d14f4a3a7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1388,
                  "y":45},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13a9da6c54f548aca77d1179d1eebfff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1402,
              "y":51},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ab66c6582f40f6a8e51fce1808a3b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1402,
                  "y":51},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"071825250cbd453095a820d34e64b544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e40b73b11b437cbc4fb1be08460902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8a9b8aad3334aacbddb942f784922a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1348,
              "y":45},
            "size":{
              "width":32,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd4718c2f874a868df7c0d13368efb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1348,
                  "y":45},
                "size":{
                  "width":32,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"a8705914cee6435b8a3d09bbb2d8fddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1184,
              "y":51},
            "size":{
              "width":146,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92aa56f5fc7f42d8a4a8ffbe21190131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1184,
                  "y":51},
                "size":{
                  "width":146,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ae1a95d1b714477a9601dcf9cb0c7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1334,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7cfdf6f7e9c4993870e64f9ed4ce83e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1334,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ba3e297d56f44fd8a188f67b0885bd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1060,
              "y":83},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a54f08e555447ab4d520e9b6a0cec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":83},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95452b5fdfa04d5cbc889ea64d7a5eac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":78},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db2bf5904054a6e9eb711075c0da842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":78},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"128349310e774ca19405bc25eaab2dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1185,
              "y":83},
            "size":{
              "width":175,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b912e39cc6844e6a9750ea3e11a15f28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1185,
                  "y":83},
                "size":{
                  "width":175,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d6fddc5228d442baeff80f112437b3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":220},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15a8776aca1c413c8e6444bd49c909d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":220},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u46.png"}},
{
          "id":"0589c985328441d1999c3bb5d27f9a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":230},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955b355604364989b8c2ba53a8505ca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":230},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9faa92018b2c437e8f72ad745d82125a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":166},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6217c46f56e74bbc877685ecbb4f1e00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":166},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u50.png"}},
{
          "id":"7252e13b782e498fb3ac8265dba70e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":176},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cfc91e390f64089865a86866da15751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":176},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bf06a0ac6a74760a595a6e497f218da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":275},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c87f1902ed094a8fa3e2f545c1a2e6ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":275},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u54.png"}},
{
          "id":"01844b8d62a9486fa9c7956105cdaf37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":285},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9785352ed5e34bd08a98ea99d85ab530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":285},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f29bff765c84f8fa18cbb9339c90df5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":220},
            "size":{
              "width":1099,
              "height":190},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80794eb9fc246dd8ce15798879088a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":220},
                "size":{
                  "width":1099,
                  "height":190},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dotted"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评审流程/u58.png"}},
{
          "id":"2a4d11dbbb4e43619b85ec50c9a9f7f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":243},
            "size":{
              "width":1050,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38573be24f7848388776e34da511090a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":243},
                "size":{
                  "width":1050,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4a16babd3c448c6a8e5c163a8ab3f26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":444},
            "size":{
              "width":1110,
              "height":265}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29da574aa0fe484db77d3ef7aad43b02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":444},
                "size":{
                  "width":1110,
                  "height":265}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评审流程/u62.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "35fb7b0bad424874a48fa12b7a0a3811":{
      "scriptId":"u0"},
    "6b2e69149476478a895046ad4779ced9":{
      "scriptId":"u1"},
    "f2e765746ba04275b44f50aeea1286c6":{
      "scriptId":"u2"},
    "0f6e064aa87f4556a4d36ead92e90c90":{
      "scriptId":"u3"},
    "5fc64044291f48a0a6fc27456f0ef42a":{
      "scriptId":"u4"},
    "d64aec64a49a4a378aa527af5820d7fc":{
      "scriptId":"u5"},
    "34f712fbef9d4433b051675901c11ee6":{
      "scriptId":"u6"},
    "1e7fcc90b1c54554b4813bc07bb1ddbf":{
      "scriptId":"u7"},
    "72fb0da261a549f1b06e11f08449a18c":{
      "scriptId":"u8"},
    "b03b580487ab42abb23aeae1fd78cfe6":{
      "scriptId":"u9"},
    "551f4d9b679e4f8ba0c052769c290213":{
      "scriptId":"u10"},
    "4f9af48934a846a780aa888789861152":{
      "scriptId":"u11"},
    "9fcfaa273d184ee08bf6a78ff937a610":{
      "scriptId":"u12"},
    "6de8cc9d10204c789ff3a22daae6189b":{
      "scriptId":"u13"},
    "d2a413c9ac804dc7a116cd17724e03d0":{
      "scriptId":"u14"},
    "1861558fc9bf416ca26389d317415a4a":{
      "scriptId":"u15"},
    "5e2985c17d324f96bf7b36db1aeb1816":{
      "scriptId":"u16"},
    "b1f3e08ca4484239b18f1764c4ce581d":{
      "scriptId":"u17"},
    "b7224456d222491a935f72f7d8f12ad1":{
      "scriptId":"u18"},
    "ff9334a59f5e4429a61817b9fbb99c86":{
      "scriptId":"u19"},
    "83dcada727b0418bbc8110f281107452":{
      "scriptId":"u20"},
    "fc7dece7c6b8451c80dd885e53266ee5":{
      "scriptId":"u21"},
    "be2f0919ba02447a87441f6e5745e9a1":{
      "scriptId":"u22"},
    "7aa277e2f473446d809e73c0f5571a11":{
      "scriptId":"u23"},
    "b67cf3005b6e486b9b57b58e19507da5":{
      "scriptId":"u24"},
    "f9da2e4730c54cb6bda71fa8d189a55d":{
      "scriptId":"u25"},
    "6d3e60a1a2dc4edabf26676139ba9fc2":{
      "scriptId":"u26"},
    "b6b8ba60956d45c6af42657cb46bc7cf":{
      "scriptId":"u27"},
    "47c889ecc5104da788a1940e8c3bed58":{
      "scriptId":"u28"},
    "b006e01e422742d5acfa8d14f4a3a7f6":{
      "scriptId":"u29"},
    "13a9da6c54f548aca77d1179d1eebfff":{
      "scriptId":"u30"},
    "a5ab66c6582f40f6a8e51fce1808a3b9":{
      "scriptId":"u31"},
    "071825250cbd453095a820d34e64b544":{
      "scriptId":"u32"},
    "70e40b73b11b437cbc4fb1be08460902":{
      "scriptId":"u33"},
    "f8a9b8aad3334aacbddb942f784922a5":{
      "scriptId":"u34"},
    "4cd4718c2f874a868df7c0d13368efb4":{
      "scriptId":"u35"},
    "a8705914cee6435b8a3d09bbb2d8fddd":{
      "scriptId":"u36"},
    "92aa56f5fc7f42d8a4a8ffbe21190131":{
      "scriptId":"u37"},
    "2ae1a95d1b714477a9601dcf9cb0c7cd":{
      "scriptId":"u38"},
    "b7cfdf6f7e9c4993870e64f9ed4ce83e":{
      "scriptId":"u39"},
    "7ba3e297d56f44fd8a188f67b0885bd8":{
      "scriptId":"u40"},
    "52a54f08e555447ab4d520e9b6a0cec7":{
      "scriptId":"u41"},
    "95452b5fdfa04d5cbc889ea64d7a5eac":{
      "scriptId":"u42"},
    "4db2bf5904054a6e9eb711075c0da842":{
      "scriptId":"u43"},
    "128349310e774ca19405bc25eaab2dac":{
      "scriptId":"u44"},
    "b912e39cc6844e6a9750ea3e11a15f28":{
      "scriptId":"u45"},
    "2d6fddc5228d442baeff80f112437b3e":{
      "scriptId":"u46"},
    "15a8776aca1c413c8e6444bd49c909d0":{
      "scriptId":"u47"},
    "0589c985328441d1999c3bb5d27f9a63":{
      "scriptId":"u48"},
    "955b355604364989b8c2ba53a8505ca8":{
      "scriptId":"u49"},
    "9faa92018b2c437e8f72ad745d82125a":{
      "scriptId":"u50"},
    "6217c46f56e74bbc877685ecbb4f1e00":{
      "scriptId":"u51"},
    "7252e13b782e498fb3ac8265dba70e4b":{
      "scriptId":"u52"},
    "6cfc91e390f64089865a86866da15751":{
      "scriptId":"u53"},
    "0bf06a0ac6a74760a595a6e497f218da":{
      "scriptId":"u54"},
    "c87f1902ed094a8fa3e2f545c1a2e6ed":{
      "scriptId":"u55"},
    "01844b8d62a9486fa9c7956105cdaf37":{
      "scriptId":"u56"},
    "9785352ed5e34bd08a98ea99d85ab530":{
      "scriptId":"u57"},
    "6f29bff765c84f8fa18cbb9339c90df5":{
      "scriptId":"u58"},
    "d80794eb9fc246dd8ce15798879088a8":{
      "scriptId":"u59"},
    "2a4d11dbbb4e43619b85ec50c9a9f7f5":{
      "scriptId":"u60"},
    "38573be24f7848388776e34da511090a":{
      "scriptId":"u61"},
    "b4a16babd3c448c6a8e5c163a8ab3f26":{
      "scriptId":"u62"},
    "29da574aa0fe484db77d3ef7aad43b02":{
      "scriptId":"u63"}}});