$axure.loadCurrentPage({
  "url":"在线问题解答.html",
  "generationDate":new Date(1477474344752.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1cb9d80574424c7fa0d15badd873b9a7",
    "type":"Axure:Page",
    "name":"在线问题解答",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c35c34ffdf634bd29237f9debf686ac5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":30,
              "y":125},
            "size":{
              "width":1176,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e9553699344335a57cd86f2652a44f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":30,
                  "y":125},
                "size":{
                  "width":1176,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息提示/u0.png"}},
{
          "id":"7bddb9d7ca614ea2bdca90cad8cf4da3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":151,
              "y":136},
            "size":{
              "width":100,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e24fe8968cd44d3fa65308fda4442380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":151,
                  "y":136},
                "size":{
                  "width":100,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 page4",
                      "target":{
                        "targetType":"page",
                        "url":"page4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息提示/u2.png"}},
{
          "id":"a9d8c045574643ccb1d24c888e86a814",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":166,
              "y":144},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40a9d409baf644898d73af0b44e586ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":144},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 page4",
                      "target":{
                        "targetType":"page",
                        "url":"page4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37a715e9634f4cb6a966ca00d87af262",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF009DD9},
{
                  "color":0xFF009DD9},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":260,
              "y":135},
            "size":{
              "width":125,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fcaa8c3543c4a16970fac358b8bab8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF009DD9},
{
                      "color":0xFF009DD9},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":260,
                  "y":135},
                "size":{
                  "width":125,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/常见问题解答/u6.png"}},
{
          "id":"c60dcd45e8a645e782411443acd6a7c3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":41,
              "y":136},
            "size":{
              "width":100,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e733660fd7644b892f0264d6c4ecb97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":41,
                  "y":136},
                "size":{
                  "width":100,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息提示/u2.png"}},
{
          "id":"fec2e30ded1a450e8cf1b0e17051b089",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":56,
              "y":144},
            "size":{
              "width":70,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b19dc190809545d9a42f3477b7d8fc71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":144},
                "size":{
                  "width":70,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page 3",
                      "target":{
                        "targetType":"page",
                        "url":"page_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edde0b7c26e040a5985b880e42974e67",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1470,
              "height":116},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db4ba6454d1d4a349d4d916fd766e044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1470,
                  "height":116},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u0.png"}},
{
          "id":"9d686c0d8f3b4fb89d2612fe0a3307a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'汉真广标 regular', '汉真广标'",
            "location":{
              "x":133,
              "y":42},
            "size":{
              "width":199,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"019b300c2ed3410480518949242c3ac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'汉真广标 regular', '汉真广标'",
                "location":{
                  "x":133,
                  "y":42},
                "size":{
                  "width":199,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de896b9104d4c9697b42cddf45d2b7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":136},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbeb16ec17742c49dcfa1c86ba0ba6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":136},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1bca63d4b4646f4baf2a5c33045d8e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":30,
              "y":175},
            "size":{
              "width":1176,
              "height":595},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b99080640843578fe8a6a2a8be45e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":30,
                  "y":175},
                "size":{
                  "width":1176,
                  "height":595},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page5/u16.png"}},
{
          "id":"67eb111f8bff4eb5bed5962fc5f4048b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":191},
            "size":{
              "width":1165,
              "height":559},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6efbfe7b1f9944f19fb926b0a3b88f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":191},
                "size":{
                  "width":1165,
                  "height":559},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评审流程/u20.png"}},
{
          "id":"0664587ffdc64628a8f4e4929608eb14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":275,
              "y":143},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b63d058b7f56479cafbf6d4b33ef0cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":275,
                  "y":143},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20c2dfeaefa348eb82a7ca90e1ef7ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1206,
              "y":126},
            "size":{
              "width":294,
              "height":644},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d3a049b46934693a4ac7a7bfa3c236a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1206,
                  "y":126},
                "size":{
                  "width":294,
                  "height":644},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page5/u395.png"}},
{
          "id":"ecb3a196c2f94280be6f2b7e6cf114cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1043,
              "y":51},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a61e193f1d9b46daab13ff6438b48150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":51},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9db44078c814f1fa73c55eb7ec37df7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1388,
              "y":45},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8681589d74524f1aa5f0c81c21b573eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1388,
                  "y":45},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af89474107874fe082844289f722c7ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1402,
              "y":51},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c3a4cb511654dfb8a973dfb5000dfba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1402,
                  "y":51},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9aebce3782042cdb270640aadb76fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a36d72dafb2f4fe0986b024344ef9956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd04229817114655895e478e0da885f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1348,
              "y":45},
            "size":{
              "width":32,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde0c68de02343a7b72538d7d13a06a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1348,
                  "y":45},
                "size":{
                  "width":32,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"796a30812c6e4042b0e077864f1343ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1184,
              "y":51},
            "size":{
              "width":146,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03eb0c88e00e43209f87b0548b8911b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1184,
                  "y":51},
                "size":{
                  "width":146,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10e8689a4ae149efb6767423674b70a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1334,
              "y":46},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f844f255008147d08bc463e8f23f2e97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1334,
                  "y":46},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39d51a6a86484d3099526a1f50a2d3f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1060,
              "y":83},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7598862451a2455bb5b088a1cc32927c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":83},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05ec7b91f53947b9ba17fe74422681ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1171,
              "y":78},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc654124e7a843a98dc5636886669702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1171,
                  "y":78},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f215f395dc54c6d8e5138c7e5382e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1185,
              "y":83},
            "size":{
              "width":175,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b03e224a3a453ab771dbf0d1567fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1185,
                  "y":83},
                "size":{
                  "width":175,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b7c2d99cf8e44ec8857c590e79bcfb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":220},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb822558b924640b1f9a863312eea14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":220},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u46.png"}},
{
          "id":"874137b7a31749079b4186a89f54ae3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":230},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32fe754e8de74445998276919ebbdc69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":230},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常见问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"常见问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ab0e8aba7cd4e629124687d3350961b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":166},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0991d4158d41958b5d425dcc7f54a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":166},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u50.png"}},
{
          "id":"ddad0bf84d0d4d78aa466506e6ced1e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":176},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e5c97a57184395b9bb865d3687633d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":176},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评审流程",
                      "target":{
                        "targetType":"page",
                        "url":"评审流程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e27627971d541b8a949cd408e07af4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1256,
              "y":275},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f18b6be0cb45068b731c469d7089b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1256,
                  "y":275},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u54.png"}},
{
          "id":"01ea61135c244a3c84e17560e61a565c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1303,
              "y":285},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f6c0b7a78542a1ba5845f08fb1c4d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1303,
                  "y":285},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线问题解答",
                      "target":{
                        "targetType":"page",
                        "url":"在线问题解答.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10000a54aeb04e62aaee2cdbed0477fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":220},
            "size":{
              "width":1099,
              "height":120},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fad9ce21bb348038cffc9acab490f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":220},
                "size":{
                  "width":1099,
                  "height":120},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "linePattern":"dotted"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线问题解答/u58.png"}},
{
          "id":"fbbbf8f442c948378c035d03c8250295",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":243},
            "size":{
              "width":1050,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4508c955096644aa9da2310987cff062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":243},
                "size":{
                  "width":1050,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59e383f6cf184be8a1ba5539e2a42d98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":370},
            "size":{
              "width":1099,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9982f3578f3b45a1871f42ab1c506cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":370},
                "size":{
                  "width":1099,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线问题解答/u62.png"}},
{
          "id":"264943c62151478f92cfa060fa3826a1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":600},
            "size":{
              "width":1070,
              "height":10},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/在线问题解答/u64_line.png"}},
{
          "id":"99d78fa349984ab4ac1f5b6ace62b1f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":390},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9555dccfd2974af783ede214ea879b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":390},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u54.png"}},
{
          "id":"22a4c80fd2924dff8ccf164175ee347e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":397},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff1cf465af64d9782ed772a4eca6733",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":397},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bc9e252f8e54471b9f03baaee21d2cc",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":620},
            "size":{
              "width":1060,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"838a35fe1de4442593c8ac5070b84bad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":680},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c35c34ffdf634bd29237f9debf686ac5":{
      "scriptId":"u0"},
    "56e9553699344335a57cd86f2652a44f":{
      "scriptId":"u1"},
    "7bddb9d7ca614ea2bdca90cad8cf4da3":{
      "scriptId":"u2"},
    "e24fe8968cd44d3fa65308fda4442380":{
      "scriptId":"u3"},
    "a9d8c045574643ccb1d24c888e86a814":{
      "scriptId":"u4"},
    "40a9d409baf644898d73af0b44e586ee":{
      "scriptId":"u5"},
    "37a715e9634f4cb6a966ca00d87af262":{
      "scriptId":"u6"},
    "5fcaa8c3543c4a16970fac358b8bab8a":{
      "scriptId":"u7"},
    "c60dcd45e8a645e782411443acd6a7c3":{
      "scriptId":"u8"},
    "4e733660fd7644b892f0264d6c4ecb97":{
      "scriptId":"u9"},
    "fec2e30ded1a450e8cf1b0e17051b089":{
      "scriptId":"u10"},
    "b19dc190809545d9a42f3477b7d8fc71":{
      "scriptId":"u11"},
    "edde0b7c26e040a5985b880e42974e67":{
      "scriptId":"u12"},
    "db4ba6454d1d4a349d4d916fd766e044":{
      "scriptId":"u13"},
    "9d686c0d8f3b4fb89d2612fe0a3307a0":{
      "scriptId":"u14"},
    "019b300c2ed3410480518949242c3ac2":{
      "scriptId":"u15"},
    "2de896b9104d4c9697b42cddf45d2b7b":{
      "scriptId":"u16"},
    "edbeb16ec17742c49dcfa1c86ba0ba6e":{
      "scriptId":"u17"},
    "a1bca63d4b4646f4baf2a5c33045d8e6":{
      "scriptId":"u18"},
    "48b99080640843578fe8a6a2a8be45e2":{
      "scriptId":"u19"},
    "67eb111f8bff4eb5bed5962fc5f4048b":{
      "scriptId":"u20"},
    "6efbfe7b1f9944f19fb926b0a3b88f65":{
      "scriptId":"u21"},
    "0664587ffdc64628a8f4e4929608eb14":{
      "scriptId":"u22"},
    "b63d058b7f56479cafbf6d4b33ef0cc5":{
      "scriptId":"u23"},
    "20c2dfeaefa348eb82a7ca90e1ef7ed8":{
      "scriptId":"u24"},
    "3d3a049b46934693a4ac7a7bfa3c236a":{
      "scriptId":"u25"},
    "ecb3a196c2f94280be6f2b7e6cf114cd":{
      "scriptId":"u26"},
    "a61e193f1d9b46daab13ff6438b48150":{
      "scriptId":"u27"},
    "a9db44078c814f1fa73c55eb7ec37df7":{
      "scriptId":"u28"},
    "8681589d74524f1aa5f0c81c21b573eb":{
      "scriptId":"u29"},
    "af89474107874fe082844289f722c7ca":{
      "scriptId":"u30"},
    "4c3a4cb511654dfb8a973dfb5000dfba":{
      "scriptId":"u31"},
    "b9aebce3782042cdb270640aadb76fd4":{
      "scriptId":"u32"},
    "a36d72dafb2f4fe0986b024344ef9956":{
      "scriptId":"u33"},
    "bd04229817114655895e478e0da885f3":{
      "scriptId":"u34"},
    "fde0c68de02343a7b72538d7d13a06a3":{
      "scriptId":"u35"},
    "796a30812c6e4042b0e077864f1343ee":{
      "scriptId":"u36"},
    "03eb0c88e00e43209f87b0548b8911b1":{
      "scriptId":"u37"},
    "10e8689a4ae149efb6767423674b70a0":{
      "scriptId":"u38"},
    "f844f255008147d08bc463e8f23f2e97":{
      "scriptId":"u39"},
    "39d51a6a86484d3099526a1f50a2d3f3":{
      "scriptId":"u40"},
    "7598862451a2455bb5b088a1cc32927c":{
      "scriptId":"u41"},
    "05ec7b91f53947b9ba17fe74422681ca":{
      "scriptId":"u42"},
    "cc654124e7a843a98dc5636886669702":{
      "scriptId":"u43"},
    "2f215f395dc54c6d8e5138c7e5382e1b":{
      "scriptId":"u44"},
    "86b03e224a3a453ab771dbf0d1567fac":{
      "scriptId":"u45"},
    "2b7c2d99cf8e44ec8857c590e79bcfb4":{
      "scriptId":"u46"},
    "2bb822558b924640b1f9a863312eea14":{
      "scriptId":"u47"},
    "874137b7a31749079b4186a89f54ae3c":{
      "scriptId":"u48"},
    "32fe754e8de74445998276919ebbdc69":{
      "scriptId":"u49"},
    "3ab0e8aba7cd4e629124687d3350961b":{
      "scriptId":"u50"},
    "ec0991d4158d41958b5d425dcc7f54a2":{
      "scriptId":"u51"},
    "ddad0bf84d0d4d78aa466506e6ced1e7":{
      "scriptId":"u52"},
    "43e5c97a57184395b9bb865d3687633d":{
      "scriptId":"u53"},
    "1e27627971d541b8a949cd408e07af4c":{
      "scriptId":"u54"},
    "11f18b6be0cb45068b731c469d7089b2":{
      "scriptId":"u55"},
    "01ea61135c244a3c84e17560e61a565c":{
      "scriptId":"u56"},
    "83f6c0b7a78542a1ba5845f08fb1c4d7":{
      "scriptId":"u57"},
    "10000a54aeb04e62aaee2cdbed0477fb":{
      "scriptId":"u58"},
    "6fad9ce21bb348038cffc9acab490f62":{
      "scriptId":"u59"},
    "fbbbf8f442c948378c035d03c8250295":{
      "scriptId":"u60"},
    "4508c955096644aa9da2310987cff062":{
      "scriptId":"u61"},
    "59e383f6cf184be8a1ba5539e2a42d98":{
      "scriptId":"u62"},
    "9982f3578f3b45a1871f42ab1c506cdb":{
      "scriptId":"u63"},
    "264943c62151478f92cfa060fa3826a1":{
      "scriptId":"u64"},
    "99d78fa349984ab4ac1f5b6ace62b1f9":{
      "scriptId":"u65"},
    "9555dccfd2974af783ede214ea879b5e":{
      "scriptId":"u66"},
    "22a4c80fd2924dff8ccf164175ee347e":{
      "scriptId":"u67"},
    "0ff1cf465af64d9782ed772a4eca6733":{
      "scriptId":"u68"},
    "1bc9e252f8e54471b9f03baaee21d2cc":{
      "scriptId":"u69"},
    "838a35fe1de4442593c8ac5070b84bad":{
      "scriptId":"u70"}}});